Nama : M Ilham Anggis Bangkit Pamungkas
NIM  : 200411100197
Nama : 200411100181

In [1]:
!pip install pandas
!pip install scikit-learn
!pip install openpyxl

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pandas as pd

df = pd.read_csv('BBRI.JK.csv')
df

In [95]:
data = df['Volume']
data

0      160729900
1      240023000
2      185763100
3       95058800
4      103964600
         ...    
243     77251000
244     92314200
245    108831400
246     79137600
247     17404500
Name: Volume, Length: 248, dtype: int64

In [96]:
n = len(data)
sizeTrain = (round(n*0.8))
data_train = pd.DataFrame(data[:sizeTrain])
data_test = pd.DataFrame(data[sizeTrain:])
data_train

Volume
0    160729900
1    240023000
2    185763100
3     95058800
4    103964600
..         ...
193  107761200
194  155984500
195  267753300
196  113829400
197  214639300

[198 rows x 1 columns]

In [97]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
train_scaled = scaler.fit_transform(data_train)
test_scaled = scaler.transform(data_test)

train = pd.DataFrame(train_scaled, columns = ['data'])
train = train['data']

test = pd.DataFrame(test_scaled, columns = ['data'])
test = test['data']
train


0      0.212603
1      0.356505
2      0.258034
3      0.093422
4      0.109585
         ...   
193    0.116475
194    0.203991
195    0.406831
196    0.127488
197    0.310439
Name: data, Length: 198, dtype: float64

In [98]:
test

0     0.403837
1     0.183921
2     0.111858
3     0.178250
4     0.100298
5     0.214113
6     0.163207
7     0.080790
8     0.137446
9     0.080634
10    0.027777
11    0.043001
12    0.274507
13    0.177305
14    0.265899
15    0.140921
16    0.094673
17    0.416962
18    0.149479
19    0.378082
20    0.073799
21    0.253972
22    0.175857
23    0.252293
24    0.116553
25    0.107811
26    0.117579
27    0.076291
28    0.089007
29    0.218053
30    0.054499
31    0.131126
32    0.257869
33    0.216099
34    0.384142
35    0.261070
36    0.328138
37    0.200395
38    0.147849
39    0.043160
40    1.551434
41    0.384544
42    0.087906
43    0.193815
44    0.089312
45    0.061105
46    0.088441
47    0.118417
48    0.064528
49   -0.047506
Name: data, dtype: float64

In [99]:
from numpy import array

def split_sequence(sequence, n_steps):
  X, y = list(), list()
  for i in range(len(sequence)):
    # find the end of this pattern
    end_ix = i + n_steps
    # check if we are beyond the sequence
    if end_ix > len(sequence)-1:
      break
    # gather input and output parts of the pattern
    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
    X.append(seq_x)
    y.append(seq_y)

  return array(X), array(y)

In [100]:
import numpy
from numpy import  array

In [101]:
from numpy import array
X, Y = split_sequence(train, 2)
# for i in range(len(df_X)):
#   print(df_X[i], df_Y[i])
x = pd.DataFrame(X, columns = ['xt-2','xt-1'])
y = pd.DataFrame(Y, columns = ['xt'])
dataset_train = pd.concat([x, y], axis=1)
dataset_train
dataset_train.to_excel('data-train.xlsx', index=False)

In [102]:
X_train = dataset_train.iloc[:, :2].values
Y_train = dataset_train.iloc[:, -1].values
X_train

array([[0.21260323, 0.35650542],
       [0.35650542, 0.25803382],
       [0.25803382, 0.09342243],
       [0.09342243, 0.10958479],
       [0.10958479, 0.11365705],
       [0.11365705, 0.15247991],
       [0.15247991, 0.04083839],
       [0.04083839, 0.1973156 ],
       [0.1973156 , 0.24491761],
       [0.24491761, 0.33565884],
       [0.33565884, 0.35635315],
       [0.35635315, 0.20158658],
       [0.20158658, 0.36890168],
       [0.36890168, 0.24875159],
       [0.24875159, 0.14832108],
       [0.14832108, 0.23328775],
       [0.23328775, 0.12582628],
       [0.12582628, 0.06766823],
       [0.06766823, 0.02269261],
       [0.02269261, 0.22170506],
       [0.22170506, 0.26341764],
       [0.26341764, 0.08671488],
       [0.08671488, 0.16642457],
       [0.16642457, 0.14395972],
       [0.14395972, 0.3205732 ],
       [0.3205732 , 0.15756991],
       [0.15756991, 0.07800069],
       [0.07800069, 0.0315264 ],
       [0.0315264 , 0.0982335 ],
       [0.0982335 , 0.08164792],
       [0.

In [103]:
test_x, test_y = split_sequence(test, 2)
# for i in range(len(test_x)):
#   print(test_x[i], test_y[i])
x = pd.DataFrame(test_x, columns = ['xt-2','xt-1'])
y = pd.DataFrame(test_y, columns = ['xt'])
dataset_test = pd.concat([x, y], axis=1)
dataset_test
dataset_test.to_excel('data-test.xlsx', index=False)

In [104]:
X_test = dataset_test.iloc[:, :2].values
Y_test = dataset_test.iloc[:, -1].values
print(len(X_test))

48


In [105]:
from sklearn.neighbors import KNeighborsRegressor
neigh = KNeighborsRegressor(n_neighbors=3)
neigh.fit(X_train,Y_train)

KNeighborsRegressor(n_neighbors=3)

In [106]:
y_pred=neigh.predict(X_test)
reshaped_data = y_pred.reshape(-1, 1)
original_data = scaler.inverse_transform(reshaped_data)
reshaped_datates = Y_test.reshape(-1, 1)
actual_test = scaler.inverse_transform(reshaped_datates)
# print(original_data)
# print(actual_test)
akhir1 = pd.DataFrame(original_data)
akhir1.to_excel('prediksi.xlsx', index=False)
akhir = pd.DataFrame(actual_test)
akhir.to_excel('aktual.xlsx', index=False)

In [107]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(original_data, actual_test)
print(mean_absolute_percentage_error(original_data, actual_test))

0.49484943336320125


#skenario uji cona

##menggunakan 2 fitur dengan k 3,5,7

In [108]:
from sklearn.neighbors import KNeighborsRegressor
neigh = KNeighborsRegressor(n_neighbors=3)
neigh.fit(X_train,Y_train)
y_pred=neigh.predict(X_test)
reshaped_data = y_pred.reshape(-1, 1)
original_data = scaler.inverse_transform(reshaped_data)
reshaped_datates = Y_test.reshape(-1, 1)
actual_test = scaler.inverse_transform(reshaped_datates)
# print(original_data)
# print(actual_test)
akhir1 = pd.DataFrame(original_data)
akhir1.to_excel('prediksi.xlsx', index=False)
akhir = pd.DataFrame(actual_test)
akhir.to_excel('aktual.xlsx', index=False)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(original_data, actual_test)
print(mean_absolute_percentage_error(original_data, actual_test))

0.49484943336320125


In [109]:
from sklearn.neighbors import KNeighborsRegressor
neigh = KNeighborsRegressor(n_neighbors=5)
neigh.fit(X_train,Y_train)
y_pred=neigh.predict(X_test)
reshaped_data = y_pred.reshape(-1, 1)
original_data = scaler.inverse_transform(reshaped_data)
reshaped_datates = Y_test.reshape(-1, 1)
actual_test = scaler.inverse_transform(reshaped_datates)
# print(original_data)
# print(actual_test)
akhir1 = pd.DataFrame(original_data)
akhir1.to_excel('prediksi.xlsx', index=False)
akhir = pd.DataFrame(actual_test)
akhir.to_excel('aktual.xlsx', index=False)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(original_data, actual_test)
print(mean_absolute_percentage_error(original_data, actual_test))

0.5200773544567113


In [110]:
from sklearn.neighbors import KNeighborsRegressor
neigh = KNeighborsRegressor(n_neighbors=7)
neigh.fit(X_train,Y_train)
y_pred=neigh.predict(X_test)
reshaped_data = y_pred.reshape(-1, 1)
original_data = scaler.inverse_transform(reshaped_data)
reshaped_datates = Y_test.reshape(-1, 1)
actual_test = scaler.inverse_transform(reshaped_datates)
# print(original_data)
# print(actual_test)
akhir1 = pd.DataFrame(original_data)
akhir1.to_excel('prediksi.xlsx', index=False)
akhir = pd.DataFrame(actual_test)
akhir.to_excel('aktual.xlsx', index=False)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(original_data, actual_test)
print(mean_absolute_percentage_error(original_data, actual_test))

0.5099399903041569


In [111]:
from sklearn.neighbors import KNeighborsRegressor
neigh = KNeighborsRegressor(n_neighbors=9)
neigh.fit(X_train,Y_train)
y_pred=neigh.predict(X_test)
reshaped_data = y_pred.reshape(-1, 1)
original_data = scaler.inverse_transform(reshaped_data)
reshaped_datates = Y_test.reshape(-1, 1)
actual_test = scaler.inverse_transform(reshaped_datates)
# print(original_data)
# print(actual_test)
akhir1 = pd.DataFrame(original_data)
akhir1.to_excel('prediksi.xlsx', index=False)
akhir = pd.DataFrame(actual_test)
akhir.to_excel('aktual.xlsx', index=False)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(original_data, actual_test)
print(mean_absolute_percentage_error(original_data, actual_test))

0.5135035827782604


##menggunakan 3 fitur dengan k 3,5,7

In [112]:
from numpy import array
df_X, df_Y = split_sequence(train, 3)
# for i in range(len(df_X)):
#   print(df_X[i], df_Y[i])
x = pd.DataFrame(df_X, columns = ['xt-3','xt-2','xt-1'])
y = pd.DataFrame(df_Y, columns = ['xt'])
dataset_train = pd.concat([x, y], axis=1)
dataset_train
dataset_train.to_excel('data-train.xlsx', index=False)

In [113]:
X_train = dataset_train.iloc[:, :3].values
Y_train = dataset_train.iloc[:, -1].values
X_train

array([[0.21260323, 0.35650542, 0.25803382],
       [0.35650542, 0.25803382, 0.09342243],
       [0.25803382, 0.09342243, 0.10958479],
       [0.09342243, 0.10958479, 0.11365705],
       [0.10958479, 0.11365705, 0.15247991],
       [0.11365705, 0.15247991, 0.04083839],
       [0.15247991, 0.04083839, 0.1973156 ],
       [0.04083839, 0.1973156 , 0.24491761],
       [0.1973156 , 0.24491761, 0.33565884],
       [0.24491761, 0.33565884, 0.35635315],
       [0.33565884, 0.35635315, 0.20158658],
       [0.35635315, 0.20158658, 0.36890168],
       [0.20158658, 0.36890168, 0.24875159],
       [0.36890168, 0.24875159, 0.14832108],
       [0.24875159, 0.14832108, 0.23328775],
       [0.14832108, 0.23328775, 0.12582628],
       [0.23328775, 0.12582628, 0.06766823],
       [0.12582628, 0.06766823, 0.02269261],
       [0.06766823, 0.02269261, 0.22170506],
       [0.02269261, 0.22170506, 0.26341764],
       [0.22170506, 0.26341764, 0.08671488],
       [0.26341764, 0.08671488, 0.16642457],
       [0.

In [114]:
test_x, test_y = split_sequence(test, 3)
# for i in range(len(test_x)):
#   print(test_x[i], test_y[i])
x = pd.DataFrame(test_x, columns = ['xt-3','xt-2','xt-1'])
y = pd.DataFrame(test_y, columns = ['xt'])
dataset_test = pd.concat([x, y], axis=1)
dataset_test
dataset_test.to_excel('data-test.xlsx', index=False)

In [115]:
X_test = dataset_test.iloc[:, :3].values
Y_test = dataset_test.iloc[:, -1].values
X_test
# print(len(X_test))

array([[0.40383739, 0.18392064, 0.11185785],
       [0.18392064, 0.11185785, 0.1782499 ],
       [0.11185785, 0.1782499 , 0.10029767],
       [0.1782499 , 0.10029767, 0.21411297],
       [0.10029767, 0.21411297, 0.16320727],
       [0.21411297, 0.16320727, 0.08078951],
       [0.16320727, 0.08078951, 0.13744563],
       [0.08078951, 0.13744563, 0.08063434],
       [0.13744563, 0.08063434, 0.02777699],
       [0.08063434, 0.02777699, 0.0430011 ],
       [0.02777699, 0.0430011 , 0.27450652],
       [0.0430011 , 0.27450652, 0.17730492],
       [0.27450652, 0.17730492, 0.2658994 ],
       [0.17730492, 0.2658994 , 0.14092063],
       [0.2658994 , 0.14092063, 0.09467265],
       [0.14092063, 0.09467265, 0.4169623 ],
       [0.09467265, 0.4169623 , 0.14947911],
       [0.4169623 , 0.14947911, 0.37808173],
       [0.14947911, 0.37808173, 0.07379939],
       [0.37808173, 0.07379939, 0.25397154],
       [0.07379939, 0.25397154, 0.17585706],
       [0.25397154, 0.17585706, 0.25229265],
       [0.

In [116]:
from sklearn.neighbors import KNeighborsRegressor
neigh = KNeighborsRegressor(n_neighbors=3)
neigh.fit(X_train,Y_train)
y_pred=neigh.predict(X_test)
reshaped_data = y_pred.reshape(-1, 1)
original_data = scaler.inverse_transform(reshaped_data)
reshaped_datates = Y_test.reshape(-1, 1)
actual_test = scaler.inverse_transform(reshaped_datates)
# print(original_data)
# print(actual_test)
akhir1 = pd.DataFrame(original_data)
akhir1.to_excel('prediksi.xlsx', index=False)
akhir = pd.DataFrame(actual_test)
akhir.to_excel('aktual.xlsx', index=False)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(original_data, actual_test)
print(mean_absolute_percentage_error(original_data, actual_test))

0.5413937510949269


In [117]:
from sklearn.neighbors import KNeighborsRegressor
neigh = KNeighborsRegressor(n_neighbors=5)
neigh.fit(X_train,Y_train)
y_pred=neigh.predict(X_test)
reshaped_data = y_pred.reshape(-1, 1)
original_data = scaler.inverse_transform(reshaped_data)
reshaped_datates = Y_test.reshape(-1, 1)
actual_test = scaler.inverse_transform(reshaped_datates)
# print(original_data)
# print(actual_test)
akhir1 = pd.DataFrame(original_data)
akhir1.to_excel('prediksi.xlsx', index=False)
akhir = pd.DataFrame(actual_test)
akhir.to_excel('aktual.xlsx', index=False)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(original_data, actual_test)
print(mean_absolute_percentage_error(original_data, actual_test))

0.5016098004648619


In [118]:
from sklearn.neighbors import KNeighborsRegressor
neigh = KNeighborsRegressor(n_neighbors=7)
neigh.fit(X_train,Y_train)
y_pred=neigh.predict(X_test)
reshaped_data = y_pred.reshape(-1, 1)
original_data = scaler.inverse_transform(reshaped_data)
reshaped_datates = Y_test.reshape(-1, 1)
actual_test = scaler.inverse_transform(reshaped_datates)
# print(original_data)
# print(actual_test)
akhir1 = pd.DataFrame(original_data)
akhir1.to_excel('prediksi.xlsx', index=False)
akhir = pd.DataFrame(actual_test)
akhir.to_excel('aktual.xlsx', index=False)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(original_data, actual_test)
print(mean_absolute_percentage_error(original_data, actual_test))

0.4828912208315826


In [39]:
from sklearn.neighbors import KNeighborsRegressor
neigh = KNeighborsRegfitur dengan k 3,5,7)
neigh.fit(X_train,Y_train)
y_pred=neigh.predict(X_test)
reshaped_data = y_pred.reshape(-1, 1)
original_data = scaler.inverse_transform(reshaped_data)
reshaped_datates = Y_test.reshape(-1, 1)
actual_test = scaler.inverse_transform(reshaped_datates)
# print(original_data)
# print(actual_test)
akhir1 = pd.DataFrame(original_data)
akhir1.to_excel('prediksi.xlsx', index=False)
akhir = pd.DataFrame(actual_test)
akhir.to_excel('aktual.xlsx', index=False)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(original_data, actual_test)
print(mean_absolute_percentage_error(original_data, actual_test))

0.48449003098094895
